server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  ${EUREKA_SERVER_URI}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: Hjds23FDF42fsdhfjs42367hfjsdhjfdsbf2hdfsH
  expiration: 86400000
